# Generated by Django 5.1.2 on 2025-04-21 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id_libro', models.AutoField(help_text='Id único', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='titulo', max_length=250)),
                ('genero', models.CharField(help_text='genero')),
                ('descripcion', models.CharField(help_text='descripcion', max_length=3000)),
                ('publicacion', models.IntegerField(help_text='publicacion')),
                ('puntuacion', models.IntegerField(help_text='puntuacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(help_text='ID único', primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('contraseña', models.CharField(help_text='Contraseña', max_length=50)),
                ('genero_uno', models.CharField(max_length=50)),
                ('genero_dos', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recomendacion',
            fields=[
                ('id_recomendacion', models.AutoField(help_text='Id único', primary_key=True, serialize=False)),
                ('motivo', models.CharField(help_text='motivo')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_general.libro', verbose_name='libro')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_general.usuario', verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='interaccion',
            fields=[
                ('id_interaccion', models.AutoField(help_text='Id único', primary_key=True, serialize=False)),
                ('interaccion', models.CharField(help_text='interaccion')),
                ('calificacion', models.IntegerField(help_text='calificacion')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_general.libro', verbose_name='libro')),
                ('id_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_general.usuario', verbose_name='usuario')),
            ],
        ),
    ]
